version: '3'

services:
    meetapp-postgres:
        container_name: meetapp-postgres
        image: postgres
        restart: unless-stopped
        volumes: 
            - meetapp-postgres-data:/data
        environment:  
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS} 
        networks: 
            - meetapp-network
        ports:
            - '5432:5432'
    meetapp-redis:
        container_name: meetapp-redis
        image: redis:alpine
        restart: unless-stopped
        volumes:
            - meetapp-redis-data:/data
        environment: 
            - ALLOW_EMPTY_PASSWORD=yes
        networks:
            - meetapp-network
        ports:
            - '6379:6379'
    meetapp-api:
        container_name: meetapp-api
        build: .
        restart: unless-stopped
        volumes:
            - .:/home/node/api
            - /home/node/api/node_modules
        depends_on: 
            - meetapp-postgres
            - meetapp-jobs
        networks: 
            - meetapp-network
        ports: 
            - '3333:3333'
    meetapp-jobs:
        container_name: meetapp-jobs
        build: .
        restart: unless-stopped
        command: yarn queue
        depends_on: 
            - meetapp-redis
        networks:
            - meetapp-network

volumes:
    meetapp-postgres-data:
    meetapp-redis-data:

networks:
    meetapp-network:
        driver: bridge